name: level_map
description: A Flutter library to add level-map feature with powerful customization options.
version: 0.2.0
#author: Bharath
homepage: https://github.com/Bharathh-Raj/level_map

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: